language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
      env: GUZZLE_VERSION=^5.3 COMPOSER_OPTIONS="--prefer-lowest"
    - php: 5.6
      dist: xenial
      env: GUZZLE_VERSION=^6.0 COMPOSER_OPTIONS="--prefer-lowest"
    - php: 5.6
      dist: xenial
      env: GUZZLE_VERSION=^5.3
    - php: 5.6
      dist: xenial
      env: GUZZLE_VERSION=^6.0
    - php: 7.0
      dist: xenial
      env: GUZZLE_VERSION=^5.3
    - php: 7.0
      dist: xenial
      env: GUZZLE_VERSION=^6.0
    - php: 7.1
      dist: bionic
      env: GUZZLE_VERSION=^5.3
    - php: 7.1
      dist: bionic
      env: GUZZLE_VERSION=^6.0
    - php: 7.2
      dist: bionic
      env: GUZZLE_VERSION=^5.3
    - php: 7.2
      dist: bionic
      env: GUZZLE_VERSION=^6.0
    - php: 7.3
      dist: bionic
      env: GUZZLE_VERSION=^5.3
    - php: 7.3
      dist: bionic
      env: GUZZLE_VERSION=^6.0
    - php: 7.4
      dist: bionic
      env: GUZZLE_VERSION=^5.3
    - php: 7.4
      dist: bionic
      env: GUZZLE_VERSION=^6.0

before_install:
  - composer require "guzzlehttp/guzzle:${GUZZLE_VERSION}" --no-update

install:
  - travis_retry composer update $COMPOSER_OPTIONS

script:
  - make test
